blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('category/list', views.CategoryListView.as_view(), name='category_list'),
    path('category/create', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/<slug:slug>/update', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<slug:slug>/delete', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('', views.ReservationCreateView.as_view(), name='blog_home'),
    path('room', views.BlogRoomListView.as_view(), name='blog_room'),
    path('about', views.AboutView.as_view(), name='blog_about'),
    path('contact', views.ContactView.as_view(), name='blog_contact'),
    path('articles', views.BlogArticleListView.as_view(), name='blog_article_list'),
    path('<slug:slug>', views.BlogArticleDetailView.as_view(), name='blog_article_detail'),
    path('category/<slug:slug>', views.BlogCategoryDetailView.as_view(), name='blog_category_detail'),
    path('<slug:slug>/send-comment', views.send_comment, name='blog_send_comment'),
    path('tag/<slug:slug>', views.BlogTagDetailView.as_view(), name='blog_tag_detail'),
    path('articles/search', views.ArticleSearchListView.as_view(), name='article_search_list_view'),
    path('author/<int:pk>', views.AuthorArticlesListView.as_view(), name='blog_author_articles'),

    path('article/<slug:slug>', views.DashboardArticleDetailView.as_view(), name='dashboard_article_detail'),
    path('article/list/', views.DashboardArticleListView.as_view(), name='dashboard_article_list'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<slug:slug>/update', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/<slug:slug>/delete', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/<int:pk>/update', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('myarticle/', views.UserArticlesListView.as_view(), name='my_articles'),

    path('article/category/create', views.CategoryCreatePopup, name="category_create_popup"),
    path('article/category/ajax/get_category_id', views.get_category_id, name="get_customer_id"),
]

django_hotel_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView
from django.urls import path, include, reverse_lazy, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from booking.api import ServiceViewSet, BookingTypeViewSet, BookingViewSet, CheckInViewSet, CheckOutViewSet
from customer.api import CustomerViewSet
from reservation.api import ReservationViewSet
from room.api import RoomViewSet, RoomTypeViewSet, FacilityViewSet
from blog.api import CategoryViewSet, ArticleList, CategoryArticleList, ArticleViewSet, ArticleCommentList, \
    CommentRetrieveUpdateDestroy, CommentList
from dashboard.forms import PasswordChangeForm, ResetPasswordForm, SetPasswordForm
from dashboard.views import loginrequest, registeruser, UserProfileView
from staff.api import StaffRoleViewSet, StaffViewSet

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),

    path('userprofile/', UserProfileView.as_view(), name='userprofile'),
    path('changepassword/',
         PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm,
                                    success_url=reverse_lazy('dashboard')), name='changepassword'),
    path('passwordreset/',
         PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm,
                                   success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'),
         name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm,
                                          success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),
]

urlpatterns += [
    path('booking/', include('booking.urls')),
    path('customers/', include('customer.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('reservation/', include('reservation.urls')),
    path('rooms/', include('room.urls')),
    path('staffs/', include('staff.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-catalog')
]

router = routers.DefaultRouter()
router.register(r'rooms', RoomViewSet, 'room')
router.register(r'room-types', RoomTypeViewSet, 'room-type')
router.register(r'facilities', FacilityViewSet, 'facility')
router.register(r'categories', CategoryViewSet, 'category')
router.register(r'articles', ArticleViewSet, 'article')
router.register(r'services', ServiceViewSet, 'service')
router.register(r'booking-types', BookingTypeViewSet, 'booking-type')
router.register(r'bookings', BookingViewSet, 'booking')
router.register(r'checkins', CheckInViewSet, 'checkin')
router.register(r'checkouts', CheckOutViewSet, 'checkout')
router.register(r'customers', CustomerViewSet, 'customer')
router.register(r'reservations', ReservationViewSet, 'reservation')
router.register(r'staff-roles', StaffRoleViewSet, 'staff-role')
router.register(r'staffs', StaffViewSet, 'staff')


urlpatterns += [
    path('api/articlelist/', ArticleList.as_view()),
    path('api/category-articles/<slug:slug>/', CategoryArticleList.as_view()),
    path('api/article-comments/<slug:slug>/', ArticleCommentList.as_view()),
    path('api/comments/', CommentList.as_view()),
    path('api/comments/<int:pk>/', CommentRetrieveUpdateDestroy.as_view()),
    path('api/', include(router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField('Chuyen muc', max_length=100, null=False, blank=False, unique=True, error_messages={'unique': "Chuyen muc da ton tai"})
    slug = models.SlugField()
    approved = models.BooleanField('Phe duyet', default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)


class Article(models.Model):
    # Article status constants
    DRAFTED = "DRAFTED"
    PUBLISHED = "PUBLISHED"
    HIDDEN = "HIDDEN"

    # CHOICES
    STATUS_CHOICES = (
        (DRAFTED, 'Ban thao'),
        (PUBLISHED, 'Dang tai'),
        (HIDDEN, 'An'),
    )

    # BLOG MODEL FIELDS
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=250, null=False, blank=False)
    slug = models.SlugField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(default='slider/img-slide-7.jpg', upload_to='blog')
    body = RichTextUploadingField(blank=True)
    tags = TaggableManager(blank=True)
    date_published = models.DateTimeField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(default=timezone.now, verbose_name='Thoi gian cap nhat')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='DRAFT')
    views = models.PositiveIntegerField(default=0)
    published = models.BooleanField(default=False)

    class Meta:
        unique_together = ("title",)
        ordering = ('-date_published',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=False)
        super(Article, self).save(*args, **kwargs)


class Comment(models.Model):

    name = models.CharField(max_length=250, null=False, blank=False)
    email = models.EmailField()
    comment = models.TextField(null=False, blank=False)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.article}"

blog/forms.py
# Django imports
from django import forms
from django.forms import TextInput, Select, FileInput

# Third-party app imports
from ckeditor.fields import RichTextFormField
from taggit.forms import TagWidget, TagField
# Blog app imports
from blog.models import Article, Category, Comment


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "approved"]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ArticleCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.filter(approved=True), widget=forms.Select())
    body = RichTextFormField()

    class Meta:
        model = Article
        fields = ["title", "category", "image", "body", "tags", "status"]
        widgets = {
            'title': TextInput(attrs={'name': "article-title", 'class': "form-control", 'id': "articleTitle"}),
            'image': FileInput(attrs={"class": "clearablefileinput", "type": "file", "id": "articleImage", "name": "article-image"}),
            'tags': TextInput(attrs={'name': "tags", 'data-role': "tagsinput", 'placeholder': "Example: sports, game"}),
            'status': Select(),
        }


class ArticleUpdateForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.filter(approved=True), widget=forms.Select())
    tags = TagField(widget=TagWidget(attrs={'name': "tags", 'placeholder': "Example: sports, game", 'id': "tags", 'data-role': "tagsinput"}))
    body = RichTextFormField()

    class Meta:
        model = Article
        fields = ["title", "category", "image", "body", "tags", "status"]
        widgets = {
            'title': TextInput(attrs={'name': "article-title", 'class': "form-control", 'id': "articleTitle"}),
            'image': FileInput(attrs={"class": "clearablefileinput", "type": "file", "id": "articleImage","name": "article-image"}),
            'status': Select(),
        }


class CommentUpdateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['approved']

blog/templates/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Xoa bai viet?</h3>
                </div>
                <div class="card-body">
                    <p>Ban muon xoa bai viet {{ article.title }}?</p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <table>
                        {{ form.as_table }}
                        </table>
                        <input type="submit" value="Xoa" class="btn btn-primary btn-user">
                        <a class="btn btn-primary text-white" type="button" href="{% url 'dashboard_article_list' %}">Huy</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/article_detail.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-sm-8 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Bai viet</h3>
                    {% if perms.blog.change_article %}<a class="badge badge-primary" href="{% url 'article_update' article.slug %}">Cap nhat</a>{% endif %}
                    {% if perms.blog.delete_article %} <a class="badge badge-danger" href="{% url 'article_delete' article.slug %}">Xoa</a>{% endif %}
                </div>
                <div class="card-body">
                    <p>Ten bai viet: {{ article.title }}
                    <br>Tac gia: {{ article.author }}
                    <br>Chuyen muc: {{ article.category }}</p>
                    <div class="user-img">
                    <p>Anh thumnail: {{ article.image }}</p>
                        <img src="{% if article.image %}{{ article.image.url }}{% endif %}" class="img-fluid" alt="User-Profile-Image">
                    </div>
                    <p>Ngay viet: {{ article.date_created }}
                    <br>Ngay dang tai: {{ article.date_published }}
                    <br>Ngay cap nhat: {{ article.date_updated }}</p>
                    <p>Binh luan</p>
                    <ol>
                        {% for comment in article.comment_set.all %}
                            <li style="white-space: normal !important;">
                                <p>Nguoi viet: {{ comment.name }}
                                <br>Email: {{ comment.email }}
                                <br>Noi dung: {{ comment.comment }}
                                <br>Thoi gian binh luan: {{ comment.date_created }}
                                <br>Thoi gian cap nhat : {{ comment.date_updated }}
                                <br>Phe duyet: {{ comment.approved }}
                                <br>{% if perms.blog.change_comment %}<a class="badge badge-primary" href="{% url 'comment_update' comment.id %}">Phe duyet</a>{% endif %}
                                {% if perms.blog.change_comment %}<a class="badge badge-danger" href="{% url 'comment_delete' comment.id %}">Xoa</a>{% endif %}</p>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Xoa chuyen muc {{ category.name }}?</h3>
                </div>
                <div class="card-body">
                    <p>Ban muon xoa chuyen muc {{ category.name }}?</p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <table>
                        {{ form.as_table }}
                        </table>
                        <input type="submit" value="Xoa" class="btn btn-primary btn-user">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/category_form.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Them chuyen muc</h3>
                </div>
                <div class="card-body">
                    <form class="user" method="POST">
                        {% csrf_token %}
                        <table>
                            {% for field in form %}
                                {{ field.label }}
                                {{ field }}
                                {{ field.errors }}
                            {% endfor %}
                        </table>
                        <hr>
                        <input type="submit" value="Them" class="btn btn-primary btn-user">
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

blog/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block header_static %}
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>Danh sach chuyen muc</h3>
                    {% if perms.blog.add_category %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'category_create' %}">Them chuyen muc</a></span>
                    {% endif %}
                </div>
                <div class="card-body ">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Ten chuyen muc</th>
                                <th>Ngay tao</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for category in category_list %}
                        <tr>
                            <td>{{ category.id }}</td>
                            <td>{{ category.name }}</td>
                            <td>{{ category.date_created }}</td>
                            <td>{% if perms.blog.view_category %}<a class="badge badge-info" href="{% url 'category_detail' category.slug %}">Bai viet</a>{% endif %}
                                {% if perms.blog.change_category %}<a class="badge badge-primary" href="{% url 'category_update' category.slug %}">Cap nhat</a>{% endif %}
                                {% if perms.blog.delete_category %}<a class="badge badge-danger" href="{% url 'category_delete' category.slug %}">Xoa</a>{% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable();
} );
    </script>

{% endblock %}

blog/templates/categoty_detail.html
{% extends 'base.html' %}
{% load static %}
{% block header_static %}
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>chuyen muc {{ category.name }}</h3>
                    {% if perms.blog.add_category %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'article_create' %}">Them bai viet moi</a></span>
                    {% endif %}
                </div>
                <div class="card-body ">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Ten bai viet</th>
                                <th>Tac gia</th>
                                <th>Tags</th>
                                <th>Ngay dang</th>
                                <th>Trang thai</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for article in category.article_set.all %}
                            <tr>
                                <td style="white-space: normal !important;">{{ article.title }}</td>
                                <td>{{ article.author }}</td>
                                <td style="white-space: normal !important;">{{ article.tags.all|join:', ' }}</td>
                                <td>{{ article.date_published }}</td>
                                <td style="white-space: normal !important;">{{ article.get_status_display }}</td>
                                <td>{% if perms.blog.view_article %}<a href="{% url 'dashboard_article_detail' article.slug %}" class="badge badge-info">Chi tiet</a>{% endif %}
                                    {% if perms.blog.change_article %}<a class="badge badge-primary" href="{% url 'article_update' article.slug %}">Cap nhat</a>{% endif %}
                                    {% if perms.blog.delete_article %} <a class="badge badge-danger" href="{% url 'article_delete' article.slug %}">Xoa</a>{% endif %}
                                    </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable();
} );
    </script>

{% endblock %}

blog/templates/dashboard_article_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Danh sach bai viet</title>
{% endblock %}

{% block header_static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>Danh sach bai viet</h3>
                    <p class="mb-4">Tong bai viet: {{ article_list.count }}</p>
                    {% if perms.blog.add_article %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'article_create' %}">Tao bai viet moi</a></span>
                    {% endif %}
                </div>
                <div class="card-body table-responsive">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Ten bai viet</th>
                                <th>Chuyen muc</th>
                                <th>Tac gia</th>
                                <th>Tags</th>
                                <th>Ngay dang</th>
                                <th>Trang thai</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for article in article_list %}
                        <tr>
                            <td style="white-space: normal !important;">{{ article.title }}</td>
                            <td>{{ article.category }}</td>
                            <td>{{ article.author }}</td>
                            <td style="white-space: normal !important;">{{ article.tags.all|join:', ' }}</td>
                            <td>{{ article.date_published }}</td>
                            <td style="white-space: normal !important;">{{ article.get_status_display }}</td>
                            <td>{% if perms.blog.view_article %}<a href="{% url 'dashboard_article_detail' article.slug %}" class="badge badge-info">Chi tiet</a>{% endif %}
                                {% if perms.blog.change_article %}<a class="badge badge-primary" href="{% url 'article_update' article.slug %}">Cap nhat</a>{% endif %}
                                {% if perms.blog.delete_article %} <a class="badge badge-danger" href="{% url 'article_delete' article.slug %}">Xoa</a>{% endif %}
                                </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable();
} );
    </script>

{% endblock %}

blog/templates/user_articles.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Bai viet cua toi</title>
{% endblock %}

{% block header_static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>Danh sach bai viet cua toi</h3>
                    <p class="mb-4">Tong bai viet: {{ article_list.count }}</p>
                    {% if perms.blog.add_article %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'article_create' %}">Tao bai viet moi</a></span>
                    {% endif %}
                </div>
                <div class="card-body table-responsive">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Ten bai viet</th>
                                <th>Chuyen muc</th>
                                <th>Tac gia</th>
                                <th>Tags</th>
                                <th>Ngay dang</th>
                                <th>Trang thai</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for article in article_list %}
                        <tr>
                            <td style="white-space: normal !important;">{{ article.title }}</td>
                            <td>{{ article.category }}</td>
                            <td>{{ article.author }}</td>
                            <td style="white-space: normal !important;">{{ article.tags.all|join:', ' }}</td>
                            <td>{{ article.date_published }}</td>
                            <td style="white-space: normal !important;">{{ article.get_status_display }}</td>
                            <td>{% if perms.blog.view_article %}<a href="{% url 'dashboard_article_detail' article.slug %}" class="badge badge-info">Chi tiet</a>{% endif %}
                                {% if perms.blog.change_article %}<a class="badge badge-primary" href="{% url 'article_update' article.slug %}">Cap nhat</a>{% endif %}
                                {% if perms.blog.delete_article %} <a class="badge badge-danger" href="{% url 'article_delete' article.slug %}">Xoa</a>{% endif %}
                                </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable();
} );
    </script>

{% endblock %}