blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('category/list', views.CategoryListView.as_view(), name='category_list'),
    path('category/create', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/<slug:slug>/update', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<slug:slug>/delete', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('', views.ReservationCreateView.as_view(), name='blog_home'),
    path('room', views.BlogRoomListView.as_view(), name='blog_room'),
    path('about', views.AboutView.as_view(), name='blog_about'),
    path('contact', views.ContactView.as_view(), name='blog_contact'),
    path('articles', views.BlogArticleListView.as_view(), name='blog_article_list'),
    path('<slug:slug>', views.BlogArticleDetailView.as_view(), name='blog_article_detail'),
    path('category/<slug:slug>', views.BlogCategoryDetailView.as_view(), name='blog_category_detail'),
    path('<slug:slug>/send-comment', views.send_comment, name='blog_send_comment'),
    path('tag/<slug:slug>', views.BlogTagDetailView.as_view(), name='blog_tag_detail'),
    path('articles/search', views.ArticleSearchListView.as_view(), name='article_search_list_view'),
    path('author/<int:pk>', views.AuthorArticlesListView.as_view(), name='blog_author_articles'),

    path('article/<slug:slug>', views.DashboardArticleDetailView.as_view(), name='dashboard_article_detail'),
    path('article/list/', views.DashboardArticleListView.as_view(), name='dashboard_article_list'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<slug:slug>/update', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/<slug:slug>/delete', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/<int:pk>/update', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('myarticle/', views.UserArticlesListView.as_view(), name='my_articles'),

    path('article/category/create', views.CategoryCreatePopup, name="category_create_popup"),
    path('article/category/ajax/get_category_id', views.get_category_id, name="get_customer_id"),
]

booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.BookingListView.as_view(), name='booking_list'),
    path('create', views.BookingCreateView.as_view(), name='booking_create'),
    path('<int:pk>', views.BookingDetailView.as_view(), name='booking_detail'),
    path('<int:pk>/update', views.BookingUpdateView.as_view(), name='booking_update'),
    path('<int:pk>/delete', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('<int:pk>/cancel', views.BookingCancelView.as_view(), name='booking_cancel'),

    path('checkin/list', views.CheckinListView.as_view(), name='checkin_list'),
    path('<int:pk>/checkin', views.CheckinCreateView.as_view(), name='checkin_create'),
    path('<int:pk>/checkin/detail', views.CheckinDetailView.as_view(), name='checkin_detail'),
    path('<int:pk>/checkin/update', views.CheckinUpdateView.as_view(), name='checkin_update'),
    path('<int:pk>/checkin/delete', views.CheckinDeleteView.as_view(), name='checkin_delete'),

    path('checkout/list', views.CheckoutListView.as_view(), name='checkout_list'),
    path('<int:pk>/checkout', views.CheckoutCreateView.as_view(), name='checkout_create'),
    path('<int:pk>/checkout/detail', views.CheckoutDetailView.as_view(), name='checkout_detail'),
    path('<int:pk>/checkout/update', views.CheckoutUpdateView.as_view(), name='checkout_update'),
    path('<int:pk>/checkout/delete', views.CheckoutDeleteView.as_view(), name='checkout_delete'),

    path('customer/create', views.CustomerCreatePopup, name="CustomerCreate"),
    path('customer/ajax/get_customer_id', views.get_customer_id, name="get_customer_id"),

    path('service/list', views.ServiceListView.as_view(), name='service_list'),
    path('service/create', views.ServiceCreateView.as_view(), name='service_create'),
    path('service/<int:pk>/update', views.ServiceUpdateView.as_view(), name='service_update'),
    path('service/<int:pk>/delete', views.ServiceDeleteView.as_view(), name='service_delete'),
]

django_hotel_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView
from django.urls import path, include, reverse_lazy, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from booking.api import ServiceViewSet, BookingTypeViewSet, BookingViewSet, CheckInViewSet, CheckOutViewSet
from customer.api import CustomerViewSet
from reservation.api import ReservationViewSet
from room.api import RoomViewSet, RoomTypeViewSet, FacilityViewSet
from blog.api import CategoryViewSet, ArticleList, CategoryArticleList, ArticleViewSet, ArticleCommentList, \
    CommentRetrieveUpdateDestroy, CommentList
from dashboard.forms import PasswordChangeForm, ResetPasswordForm, SetPasswordForm
from dashboard.views import loginrequest, registeruser, UserProfileView
from staff.api import StaffRoleViewSet, StaffViewSet

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),

    path('userprofile/', UserProfileView.as_view(), name='userprofile'),
    path('changepassword/',
         PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm,
                                    success_url=reverse_lazy('dashboard')), name='changepassword'),
    path('passwordreset/',
         PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm,
                                   success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'),
         name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm,
                                          success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),
]

urlpatterns += [
    path('booking/', include('booking.urls')),
    path('customers/', include('customer.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('reservation/', include('reservation.urls')),
    path('rooms/', include('room.urls')),
    path('staffs/', include('staff.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-catalog')
]

router = routers.DefaultRouter()
router.register(r'rooms', RoomViewSet, 'room')
router.register(r'room-types', RoomTypeViewSet, 'room-type')
router.register(r'facilities', FacilityViewSet, 'facility')
router.register(r'categories', CategoryViewSet, 'category')
router.register(r'articles', ArticleViewSet, 'article')
router.register(r'services', ServiceViewSet, 'service')
router.register(r'booking-types', BookingTypeViewSet, 'booking-type')
router.register(r'bookings', BookingViewSet, 'booking')
router.register(r'checkins', CheckInViewSet, 'checkin')
router.register(r'checkouts', CheckOutViewSet, 'checkout')
router.register(r'customers', CustomerViewSet, 'customer')
router.register(r'reservations', ReservationViewSet, 'reservation')
router.register(r'staff-roles', StaffRoleViewSet, 'staff-role')
router.register(r'staffs', StaffViewSet, 'staff')


urlpatterns += [
    path('api/articlelist/', ArticleList.as_view()),
    path('api/category-articles/<slug:slug>/', CategoryArticleList.as_view()),
    path('api/article-comments/<slug:slug>/', ArticleCommentList.as_view()),
    path('api/comments/', CommentList.as_view()),
    path('api/comments/<int:pk>/', CommentRetrieveUpdateDestroy.as_view()),
    path('api/', include(router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from math import ceil

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from customer.models import Customer
from reservation.models import Reservation
from room.models import Room
from staff.models import Staff


class Service(models.Model):
    service_type = models.CharField('Dich vu', max_length=50)
    service_price = models.FloatField('Gia', default=0)

    class Meta:
        ordering = ['service_price', 'service_type']

    def __str__(self):
        return self.service_type


class BookingType(models.Model):
    booking_type = models.CharField('Hinh thuc dat phong', max_length=50)

    def __str__(self):
        return self.booking_type


class Booking(models.Model):
    booking_type = models.ForeignKey(BookingType, on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Nguoi thuc hien')
    no_of_adults = models.PositiveSmallIntegerField(default=1, verbose_name='So nguoi lon')
    no_of_children = models.PositiveSmallIntegerField(default=0, verbose_name='So tre em')
    booking_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay dat phong')
    arrival_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay den')
    departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay du kien di')
    description = models.CharField("Yeu cau cua khach hang", max_length=3000, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')
    canceled = models.BooleanField(default=False, verbose_name='Huy dat truoc', blank=True, null=True)

    class Meta:
        ordering = ['arrival_date_time', 'booking_date_time']

    def get_absolute_url(self):
        return reverse('booking_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.customer}'

    def total_guest(self):
        return self.no_of_adults + self.no_of_children

    @property
    def is_over_arrival_time(self):
        if self.arrival_date_time and timezone.now() > self.arrival_date_time:
            return True
        return False


class CheckIn(models.Model):
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE, null=True)
    rooms = models.ManyToManyField(Room, verbose_name='Phong thue')
    services = models.ManyToManyField(Service, verbose_name='Dich vu')
    departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay du tra phong')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Nguoi checkin')
    checkin_time = models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check in')
    initial_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tien/ngay')

    updated_at = models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')

    class Meta:
        ordering = ['-checkin_time']

    def get_absolute_url(self):
        return reverse('checkin_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.booking.customer.customer_name}'

    def save(self, *args, **kwargs):
        initial_amount = 0
        for room in self.rooms.all():
            initial_amount += room.room_type.price
            for service in self.services.all():
                initial_amount += service.service_price
        self.initial_amount = initial_amount
        super().save(*args, **kwargs)

    @property
    def is_over_departure_time(self):
        if self.departure_date_time and timezone.now() > self.departure_date_time:
            return True
        return False


class CheckOut(models.Model):
    PAYMENT_TYPE = (
        ('Tien mat', 'Tien mat'),
        ('Chuyen khoan', 'Chuyen khoan'),
        ('The thanh toan', 'The thanh toan'),
    )
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    checkin = models.OneToOneField(CheckIn, on_delete=models.CASCADE)

    checkout_time = models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check out')
    stay_duration = models.DurationField(null=True, editable=False, verbose_name='Thoi gian luu tru')
    total_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tong chi phi')
    pay_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Thanh tien')

    extra_fee = models.FloatField('Phu phi', default=0)
    discount = models.FloatField('Khuyen mai', default=0)
    vat = models.FloatField("VAT", default=10)
    payment_type = models.CharField('Hinh thuc thanh toan', choices=PAYMENT_TYPE, max_length=20, default='Tien mat')
    checkout_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Nguoi thanh toan")

    class Meta:
        ordering = ['checkout_time']

    def get_absolute_url(self):
        return reverse('checkout_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.checkin.booking.customer.customer_name}'

    def save(self, *args, **kwargs):
        stay_time = self.checkout_time - self.checkin.checkin_time
        calculated_duration = timezone.timedelta(days=ceil(stay_time.total_seconds() / 3600 / 24))
        self.stay_duration = calculated_duration
        self.total_amount = calculated_duration.days * self.checkin.initial_amount + self.extra_fee
        amount_with_vat = self.total_amount + self.total_amount * self.vat / 100
        self.pay_amount = amount_with_vat - amount_with_vat * self.discount / 100
        super().save(*args, **kwargs)

customer/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class Customer(models.Model):
    customer_name = models.CharField("Ten khach hang", max_length=100)
    customer_dob = models.DateTimeField("Ngay sinh", default=timezone.now)
    customer_adress = models.CharField('Dia chi', max_length=400, blank=True, null=True)
    phone_regex = RegexValidator(regex=r'^\+?\d{8,11}$', message="Nhap so dien thoai theo dinh dang: 0123456789")
    customer_phone = models.CharField('So dien thoai', validators=[phone_regex], max_length=13, blank=True)
    customer_email = models.EmailField("Email")
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')

    class Meta:
        ordering = ['customer_name']

    def __str__(self):
        return f'{self.customer_name}, SDT: {self.customer_phone}, Email: {self.customer_email}'

    def get_absolute_url(self):
        return reverse('customer_detail', args=[str(self.id)])

booking/templates/booking_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <!-- [ form-element ] start -->
        <div class="col-sm-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Xoa lich dat phong?</h3>
                </div>
                <div class="card-body">
                    <p>Xoa lich dat phong ma so {{ booking.id }}?</p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <table>
                        {{ form.as_table }}
                        </table>
                        <input type="submit" value="Xoa" class="btn btn-warning">
                        <a href="{% url 'booking_list' %}"><button type="button" class="btn btn-primary">Huy</button></a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

booking/templates/booking_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Lich dat phong</title>
{% endblock %}

{% block header_static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>Danh sach lich dat phong</h3>
                    <p class="mb-4">Tong so lich dat phong: {{ booking_list.count }}</p>
                    {% if perms.booking.add_booking %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'booking_create' %}">Them lich dat phong</a></span>
                    {% endif %}
                </div>
                <div class="card-body table-responsive">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Ma dat phong</th>
                                <th>Ten khach hang</th>
                                <th>So dien thoai</th>
                                <th>Ngay den</th>
                                <th>Ngay dat</th>
                                <th>Nguoi xu ly</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for booking in booking_list %}
                            <tr class="{% if not booking.checkin and booking.is_over_arrival_time and booking.canceled == False %}text-danger{% endif %}">
                                <td>{{ booking.id }}</td>
                                <td><a {% if perms.customer.view_customer %}href="{% url 'customer_detail' booking.customer.id %}"{% endif %}>{{ booking.customer.customer_name }}</a></td>
                                <td>{{ booking.customer.customer_phone }}</td>
                                <td>{{ booking.arrival_date_time|date:"d-m-Y G:i" }}</td>
                                <td>{{ booking.booking_date_time|date:"d-m-Y G:i" }}</td>
                                <td>{% if booking.user.get_full_name %}{{ booking.user.get_full_name }}{% else %}{{ booking.user }}{% endif %}</td>
                                <td>
                                    {% if booking.canceled %}
                                        <a class="badge badge-dark" href="#">Da huy</a>
                                    {% elif not booking.checkin %}
                                        <a class="badge badge-success" id="{{ booking.id }}" href="{% url 'checkin_create' booking.id %}">Checkin</a>
                                        {% if perms.booking.change_booking %}<a class="badge badge-primary" href="{% url 'booking_update' booking.id %}">Cap nhat</a>{% endif %}
                                        {% if perms.booking.change_booking %} <a class="badge badge-danger" href="{% url 'booking_cancel' booking.id %}">Huy</a>{% endif %}
                                    {% elif booking.checkin and not booking.checkin.checkout %}
                                        <a class="badge badge-warning" href="#">Da Checkin</a>
                                    {% else %}
                                        <a class="badge badge-light" href="#">Da Checkout</a>
                                    {% endif %}
                                    {% if perms.booking.view_booking %}<a href="{{ booking.get_absolute_url }}" class="badge badge-info">Chi tiet</a>{% endif %}
                                    </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable({
        "order": [[ 6, "asc" ], [ 3, "asc" ], [4, "asc"]]
    });
} );
    </script>

{% endblock %}

booking/templates/checkin_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Thong tin checkin so {{ checkin.id }}</h3>
                    {% if not checkin.checkout %}
                        <a class="badge badge-success" id="{{ checkin.id }}" href="{% url 'checkout_create' checkin.id %}">Checkout</a>
                        {% if perms.booking.change_checkin %}<a class="badge badge-primary" href="{% url 'checkin_update' checkin.id %}">Cap nhat</a>{% endif %}
                    {% else %}
                        <a class="badge badge-warning" href="#">Da Checkout</a>
                    {% endif %}
                    {% if perms.booking.delete_checkin %} <a class="badge badge-danger" href="{% url 'checkin_delete' checkin.id %}">Xoa</a>{% endif %}
                </div>
                <div class="card-body h5">
                    <p>Ten khach hang: <a href="{% if perms.customer.view_customer %}{% url 'customer_detail' checkin.booking.customer.id %}{% endif %}">{{ checkin.booking.customer.customer_name }}</a></p>
                    <p>So dien thoai khach hang: {{ checkin.booking.customer.customer_phone }}</p>
                    <p>So luong khach: {{ checkin.booking.total_guest }} ({{ checkin.booking.no_of_adults }} nguoi lon, {{ checkin.booking.no_of_children }} tre nho)</p>
                    <p>Phong thue: {{ checkin.rooms.all|join:', ' }}</p>
                    <p>Dich vu: {{ checkin.services.all|join:', ' }}</p>
                    <p>Yeu cau cua khach hang: {{ checkin.booking.description }}</p>
                    <p>Thoi gian checkin: {{ checkin.checkin_time|date:"d-m-Y G:i" }}</p>
                    <p class="{% if not checkin.checkout and checkin.is_over_departure_time %}text-danger{% endif %}">Thoi gian checkout du kien: {{ checkin.departure_date_time|date:"d-m-Y G:i" }}</p>
                    <p>Nguoi xu ly: {% if checkin.user.get_full_name %}{{ checkin.user.get_full_name }}{% else %}{{ checkin.user }}{% endif %}</p>
                    <p>Cap nhat luc: {{ checkin.updated_at|date:"d-m-Y G:i" }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

booking/templates/checkout_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Thong tin giao dich checkout ma so {{ checkout.id }}</h3>
                    {% if perms.booking.change_checkout %}<a class="badge badge-primary" href="{% url 'checkout_update' checkout.id %}">Cap nhat</a>{% endif %} {% if perms.booking.delete_checkout %} <a class="badge badge-danger" href="{% url 'checkout_delete' checkout.id %}">Xoa</a>{% endif %}
                </div>
                <div class="card-body h5">
                    <p>Ten khach hang: <a href="{% if perms.customer.view_customer %}{% url 'customer_detail' checkout.checkin.booking.customer.id %}{% endif %}">{{ checkout.checkin.booking.customer.customer_name }}</a></p>
                    <p>So dien thoai khach hang: {{ checkout.checkin.booking.customer.customer_phone }}</p>
                    <p>So luong khach: {{ checkout.checkin.booking.total_guest }} ({{ checkout.checkin.booking.no_of_adults }} nguoi lon, {{ checkout.checkin.booking.no_of_children }} tre nho)</p>
                    <p>Phong thue: {{ checkout.checkin.rooms.all|join:', ' }}</p>
                    <p>Dich vu: {{ checkout.checkin.services.all|join:', ' }}</p>
                    <p>Phi/ ngay: {{ checkout.checkin.initial_amount }}</p>
                    <p>Thoi gian check in: {{ checkout.checkin.checkin_time|date:"D d-m-Y G:i" }}</p>
                    <p>Thoi gian check out: {{ checkout.checkout_time|date:"D d-m-Y G:i" }}</p>
                    <p>Thoi gian luu tru: {{ checkout.stay_duration.days }} ngay</p>
                    <p>Phu phi: {{ checkout.extra_fee }}</p>
                    <p>So tien tam tinh: {{ checkout.total_amount }}</p>
                    <p>Khuyen mai: {{ checkout.discount }}%; Thue VAT: {{ checkout.vat }}%</p>
                    <p>Thanh tien: {{ checkout.pay_amount }}</p>
                    <p>Nguoi xu ly: {% if checkout.checkout_by.get_full_name %}{{ checkout.checkout_by.get_full_name }}{% else %}{{ checkout.checkout_by }}{% endif %}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

booking/templates/service_list.html
{% extends 'base.html' %}
{% load static %}
{% block header_static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>Danh sach dich vu</h3>
                    {% if perms.booking.add_service %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'service_create' %}">Them dich vu</a></span>
                    {% endif %}
                </div>
                <div class="card-body ">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Dich vu</th>
                                <th>Gia tien</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for service in service_list %}
                        <tr>
                            <td>{{ service.id }}</td>
                            <td>{{ service.service_type }}</td>
                            <td>{{ service.service_price }}</td>
                            <td>{% if perms.booking.change_service %}<a class="badge badge-primary" href="{% url 'service_update' service.id %}">Cap nhat</a>{% endif %}
                                {% if perms.booking.delete_service %}<a class="badge badge-danger" href="{% url 'service_delete' service.id %}">Xoa</a>{% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable();
} );
    </script>

{% endblock %}