blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('category/list', views.CategoryListView.as_view(), name='category_list'),
    path('category/create', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/<slug:slug>/update', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<slug:slug>/delete', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('', views.ReservationCreateView.as_view(), name='blog_home'),
    path('room', views.BlogRoomListView.as_view(), name='blog_room'),
    path('about', views.AboutView.as_view(), name='blog_about'),
    path('contact', views.ContactView.as_view(), name='blog_contact'),
    path('articles', views.BlogArticleListView.as_view(), name='blog_article_list'),
    path('<slug:slug>', views.BlogArticleDetailView.as_view(), name='blog_article_detail'),
    path('category/<slug:slug>', views.BlogCategoryDetailView.as_view(), name='blog_category_detail'),
    path('<slug:slug>/send-comment', views.send_comment, name='blog_send_comment'),
    path('tag/<slug:slug>', views.BlogTagDetailView.as_view(), name='blog_tag_detail'),
    path('articles/search', views.ArticleSearchListView.as_view(), name='article_search_list_view'),
    path('author/<int:pk>', views.AuthorArticlesListView.as_view(), name='blog_author_articles'),

    path('article/<slug:slug>', views.DashboardArticleDetailView.as_view(), name='dashboard_article_detail'),
    path('article/list/', views.DashboardArticleListView.as_view(), name='dashboard_article_list'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<slug:slug>/update', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/<slug:slug>/delete', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/<int:pk>/update', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('myarticle/', views.UserArticlesListView.as_view(), name='my_articles'),

    path('article/category/create', views.CategoryCreatePopup, name="category_create_popup"),
    path('article/category/ajax/get_category_id', views.get_category_id, name="get_customer_id"),
]

django_hotel_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView
from django.urls import path, include, reverse_lazy, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from booking.api import ServiceViewSet, BookingTypeViewSet, BookingViewSet, CheckInViewSet, CheckOutViewSet
from customer.api import CustomerViewSet
from reservation.api import ReservationViewSet
from room.api import RoomViewSet, RoomTypeViewSet, FacilityViewSet
from blog.api import CategoryViewSet, ArticleList, CategoryArticleList, ArticleViewSet, ArticleCommentList, \
    CommentRetrieveUpdateDestroy, CommentList
from dashboard.forms import PasswordChangeForm, ResetPasswordForm, SetPasswordForm
from dashboard.views import loginrequest, registeruser, UserProfileView
from staff.api import StaffRoleViewSet, StaffViewSet

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),

    path('userprofile/', UserProfileView.as_view(), name='userprofile'),
    path('changepassword/',
         PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm,
                                    success_url=reverse_lazy('dashboard')), name='changepassword'),
    path('passwordreset/',
         PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm,
                                   success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'),
         name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm,
                                          success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),
]

urlpatterns += [
    path('booking/', include('booking.urls')),
    path('customers/', include('customer.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('reservation/', include('reservation.urls')),
    path('rooms/', include('room.urls')),
    path('staffs/', include('staff.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-catalog')
]

router = routers.DefaultRouter()
router.register(r'rooms', RoomViewSet, 'room')
router.register(r'room-types', RoomTypeViewSet, 'room-type')
router.register(r'facilities', FacilityViewSet, 'facility')
router.register(r'categories', CategoryViewSet, 'category')
router.register(r'articles', ArticleViewSet, 'article')
router.register(r'services', ServiceViewSet, 'service')
router.register(r'booking-types', BookingTypeViewSet, 'booking-type')
router.register(r'bookings', BookingViewSet, 'booking')
router.register(r'checkins', CheckInViewSet, 'checkin')
router.register(r'checkouts', CheckOutViewSet, 'checkout')
router.register(r'customers', CustomerViewSet, 'customer')
router.register(r'reservations', ReservationViewSet, 'reservation')
router.register(r'staff-roles', StaffRoleViewSet, 'staff-role')
router.register(r'staffs', StaffViewSet, 'staff')


urlpatterns += [
    path('api/articlelist/', ArticleList.as_view()),
    path('api/category-articles/<slug:slug>/', CategoryArticleList.as_view()),
    path('api/article-comments/<slug:slug>/', ArticleCommentList.as_view()),
    path('api/comments/', CommentList.as_view()),
    path('api/comments/<int:pk>/', CommentRetrieveUpdateDestroy.as_view()),
    path('api/', include(router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views
from reservation import views


urlpatterns = [
    path('list', views.ReservationListView.as_view(), name='reservation_list'),
    path('create', views.ReservationCreateView.as_view(), name='reservation_create'),
    path('<int:pk>', views.ReservationDetailView.as_view(), name='reservation_detail'),
    path('<int:pk>/processing', views.ReservationUpdateView.as_view(), name='reservation_update'),
    path('<int:pk>/delete', views.ReservationDeleteView.as_view(), name='reservation_delete'),

    path('booking/create', views.BookingCreatePopup, name="BookingCreate"),
]

booking/models.py
from math import ceil

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from customer.models import Customer
from reservation.models import Reservation
from room.models import Room
from staff.models import Staff


class Service(models.Model):
    service_type = models.CharField('Dich vu', max_length=50)
    service_price = models.FloatField('Gia', default=0)

    class Meta:
        ordering = ['service_price', 'service_type']

    def __str__(self):
        return self.service_type


class BookingType(models.Model):
    booking_type = models.CharField('Hinh thuc dat phong', max_length=50)

    def __str__(self):
        return self.booking_type


class Booking(models.Model):
    booking_type = models.ForeignKey(BookingType, on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Nguoi thuc hien')
    no_of_adults = models.PositiveSmallIntegerField(default=1, verbose_name='So nguoi lon')
    no_of_children = models.PositiveSmallIntegerField(default=0, verbose_name='So tre em')
    booking_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay dat phong')
    arrival_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay den')
    departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay du kien di')
    description = models.CharField("Yeu cau cua khach hang", max_length=3000, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')
    canceled = models.BooleanField(default=False, verbose_name='Huy dat truoc', blank=True, null=True)

    class Meta:
        ordering = ['arrival_date_time', 'booking_date_time']

    def get_absolute_url(self):
        return reverse('booking_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.customer}'

    def total_guest(self):
        return self.no_of_adults + self.no_of_children

    @property
    def is_over_arrival_time(self):
        if self.arrival_date_time and timezone.now() > self.arrival_date_time:
            return True
        return False


class CheckIn(models.Model):
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE, null=True)
    rooms = models.ManyToManyField(Room, verbose_name='Phong thue')
    services = models.ManyToManyField(Service, verbose_name='Dich vu')
    departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay du tra phong')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Nguoi checkin')
    checkin_time = models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check in')
    initial_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tien/ngay')

    updated_at = models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')

    class Meta:
        ordering = ['-checkin_time']

    def get_absolute_url(self):
        return reverse('checkin_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.booking.customer.customer_name}'

    def save(self, *args, **kwargs):
        initial_amount = 0
        for room in self.rooms.all():
            initial_amount += room.room_type.price
            for service in self.services.all():
                initial_amount += service.service_price
        self.initial_amount = initial_amount
        super().save(*args, **kwargs)

    @property
    def is_over_departure_time(self):
        if self.departure_date_time and timezone.now() > self.departure_date_time:
            return True
        return False


class CheckOut(models.Model):
    PAYMENT_TYPE = (
        ('Tien mat', 'Tien mat'),
        ('Chuyen khoan', 'Chuyen khoan'),
        ('The thanh toan', 'The thanh toan'),
    )
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    checkin = models.OneToOneField(CheckIn, on_delete=models.CASCADE)

    checkout_time = models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check out')
    stay_duration = models.DurationField(null=True, editable=False, verbose_name='Thoi gian luu tru')
    total_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tong chi phi')
    pay_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Thanh tien')

    extra_fee = models.FloatField('Phu phi', default=0)
    discount = models.FloatField('Khuyen mai', default=0)
    vat = models.FloatField("VAT", default=10)
    payment_type = models.CharField('Hinh thuc thanh toan', choices=PAYMENT_TYPE, max_length=20, default='Tien mat')
    checkout_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Nguoi thanh toan")

    class Meta:
        ordering = ['checkout_time']

    def get_absolute_url(self):
        return reverse('checkout_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.checkin.booking.customer.customer_name}'

    def save(self, *args, **kwargs):
        stay_time = self.checkout_time - self.checkin.checkin_time
        calculated_duration = timezone.timedelta(days=ceil(stay_time.total_seconds() / 3600 / 24))
        self.stay_duration = calculated_duration
        self.total_amount = calculated_duration.days * self.checkin.initial_amount + self.extra_fee
        amount_with_vat = self.total_amount + self.total_amount * self.vat / 100
        self.pay_amount = amount_with_vat - amount_with_vat * self.discount / 100
        super().save(*args, **kwargs)

reservation/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class Reservation(models.Model):
    STATUS = (
        ('Cho xu ly', 'Cho xu ly'),
        ('Da dat phong', 'Da dat phong'),
        ('Da huy', 'Da huy'),
    )
    guest_name = models.CharField('Ho va ten', max_length=300)
    phone_regex = RegexValidator(regex=r'^\+?\d{8,11}$', message="Nhap so dien thoai theo dinh dang: 0123456789")
    guest_phone = models.CharField('So dien thoai', validators=[phone_regex], max_length=13, blank=True)
    guest_email = models.EmailField("Email", null=True, blank=True)
    no_of_children = models.PositiveSmallIntegerField("So tre nho", default=0)
    no_of_adults = models.PositiveSmallIntegerField("So nguoi lon", default=1)
    reservation_date_time = models.DateTimeField("Ngay dat", default=timezone.now)
    expected_arrival_date_time = models.DateTimeField("Ngay den du kien", default=timezone.now)
    expected_departure_date_time = models.DateTimeField("Ngay di du kien", default=timezone.now)
    status = models.CharField('Trang thai', max_length=20, choices=STATUS, default='Cho xu ly')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Nguoi xu ly')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Cap nhat luc')

    class Meta:
        ordering = ['reservation_date_time', 'expected_arrival_date_time', 'guest_name']

    def get_absolute_url(self):
        return reverse('reservation_detail', args=[str(self.id)])

    def __str__(self):
        return str(self.id)

    def total_guest(self):
        return self.no_of_adults + self.no_of_children

    @property
    def is_over_expected_arrival_time(self):
        if self.expected_arrival_date_time and timezone.now() > self.expected_arrival_date_time:
            return True
        return False

reservation/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView

from booking.forms import BookingForm
from reservation.forms import ReservationForm, ReservationUpdateForm
from reservation.models import Reservation


class ReservationListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = 'reservation_list.html'


class ReservationDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'reservation.view_reservation'
    model = Reservation
    template_name = 'reservation_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation = get_object_or_404(Reservation, id=self.kwargs['pk'])
        context['Total_guests'] = reservation.no_of_adults + reservation.no_of_children
        return context


class ReservationCreateView(CreateView):
    model = Reservation
    form_class = ReservationForm
    template_name = 'reservation_form.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('reservation_list')


class ReservationUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'reservation.change_reservation'
    model = Reservation
    form_class = ReservationUpdateForm
    template_name = 'reservation_update.html'
    success_url = reverse_lazy('reservation_list')

    def form_valid(self, form):
        form.instance.updated_at = timezone.now()
        form.instance.user = self.request.user
        reservation = super(ReservationUpdateView, self).form_valid(form)
        return reservation


def BookingCreatePopup(request):
    form = BookingForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        return HttpResponse(
            '<script>opener.closePopup(window, "%s", "%s", "#id_booking");</script>' % (instance.pk, instance))
    return render(request, "booking_form_popup.html", {"form": form})


class ReservationDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'reservation.delete_reservation'
    model = Reservation
    template_name = 'reservation_confirm_delete.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('reservation_list')

reservation/templates/booking_form_popup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    {% block title %}
	<title>Quan ly khach san</title>
    {% endblock %}
	<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 11]>

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	<!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="description" content="Flash Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
	<meta name="keywords"
		content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, Flash Able, Flash Able bootstrap admin template">
	<meta name="author" content="Codedthemes" />
	<!-- Favicon icon -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}">

    <script src="{% url 'js-catalog' %}"></script>
    <script src="{% static 'admin/js/core.js' %}"></script>
    <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>

<body class="dt-example dt-example-uikit">

    <div class="row">
        <div class="col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Dat phong</h3>
                </div>
                <div class="card-body">
                    <form class="user" method="POST" action="{% url 'booking_create' %}">
                        {% csrf_token %}
                            {{ form.media }}
                            {% if messages %}
                                {% for message in messages %}
                                <div class="container-fluid p-0">
                                    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {% endfor %}
                            {% endif %}
                            {{ form.non_field_errors }}
                            {% for hidden_field in form.hidden_fields %}
                                {{ hidden_field.errors }}
                                {{ hidden_field }}
                            {% endfor %}

                            <div class="form-group row mb-2">
                                {{ form.booking_type.errors }}
                                <label for="{{ form.booking_type.id_for_label }}" class="col-sm-4 col-form-label">Hinh thuc dat phong</label>
                                    {{ form.booking_type }}
                            </div>

                            <div class="form-group row mb-2">
                                {{ form.customer.errors }}
                                <label for="{{ form.customer.id_for_label }}" class="col-sm-3 col-form-label">Khach hang</label>
                                <div class="col-sm-6">
                                    {{ form.customer }}
                                </div>
                                <a href="{% url 'CustomerCreate' %}" id="add_customer" class="col-form-label" onclick="return showAddPopup(this);"><i class="feather icon-plus-circle"> Them khach hang</i></a>
                            </div>
                            <div class="form-group row mb-2">
                                <div class="col-sm-6 mb-3 mb-sm-0 form-group mb-2">
                                    {{ form.arrival_date_time.errors }}
                                    <label for="{{ form.arrival_date_time.id_for_label }}">Ngay den</label>
                                    {{ form.arrival_date_time }}
                                </div>
                                <div class="col-sm-6 mb-3 mb-sm-0 form-group mb-2">
                                    {{ form.departure_date_time.errors }}
                                    <label for="{{ form.departure_date_time.id_for_label }}">Ngay du kien di</label>
                                    {{ form.departure_date_time }}
                                </div>
                            </div>
                            <div class="form-group row mb-2">
                                <div class="col-sm-6 mb-3 mb-sm-0 form-group mb-2">
                                    {{ form.no_of_adults.errors }}
                                    <label for="{{ form.no_of_adults.id_for_label }}">So nguoi lon</label>
                                    {{ form.no_of_adults }}
                                </div>
                                <div class="col-sm-6 mb-3 mb-sm-0 form-group mb-2">
                                    {{ form.no_of_children.errors }}
                                    <label for="{{ form.no_of_children.id_for_label }}">So tre nho</label>
                                    {{ form.no_of_children }}
                                </div>
                            </div>

                            <div class="form-group ">
                                {{ form.description.errors }}
                                <label for="{{ form.description.id_for_label }}">Yeu cau cua khach hang</label>
                                {{ form.description }}
                            </div>
                            <br>
                        <button type="submit" class="btn btn-primary" title="" data-toggle="tooltip">Xac nhan</button>
                        <a href="{% url 'booking_list' %}"><button type="button" class="btn btn-primary">Huy</button></a>
                    </form>
                </div>
            </div>
        </div>
    </div>
	<script src="{% static 'js/pcode.min.js' %}"></script>

    <script src="{% static 'js/vendor-all.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#id_customer').select2();
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script type="text/javascript">
        function showAddPopup(triggeringLink) {
            var name = triggeringLink.id.replace(/^add_/, '');
            href = triggeringLink.href;
            var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
            win.focus();
            return false;
        }
        function closePopup(win, newID, newRepr, id) {
            $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
            win.close();
        }
    </script>

</body>
</html>

reservation/templates/reservation_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Xoa giao dich dat phong?</h3>
                </div>
                <div class="card-body">
                    <p>Xoa giao dich dat phong ma so {{ reservation.id }}?</p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <table>
                        {{ form.as_table }}
                        </table>
                        <input type="submit" value="Xoa" class="btn btn-primary btn-user">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

reservation/templates/reservation_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Danh sach dat truoc qua website</title>
{% endblock %}

{% block header_static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
	<!-- fontawesome icon -->
	<link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
	<!-- animation css -->
	<link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

	<!-- vendor css -->
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/dataTables.uikit.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card">
                <div class="card-header">
                    <h3>Danh sach lich dat phong truoc</h3>
                    <p class="mb-4">Tong so lich dat phong: {{ reservation_list.count }}</p>
                    {% if perms.reservation.add_reservation %}
                    <span class="d-block m-t-5"> <a class="collapse-item" href="{% url 'reservation_create' %}">Them lich dat phong</a></span>
                    {% endif %}
                </div>
                <div class="card-body table-responsive">
                    <table id="example" class="table table-hover table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Ten khach hang</th>
                                <th>So dien thoai</th>
                                <th>Tong so khach</th>
                                <th>Ngay dat</th>
                                <th>Trang thai</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for reservation in reservation_list %}
                            <tr class="{% if reservation.status  == 'Cho xu ly' and reservation.is_over_expected_arrival_time %}text-danger{% endif %}">
                                <td>{{ reservation.guest_name }}</td>
                                <td>{{ reservation.guest_phone }}</td>
                                <td>{{ reservation.total_guest }}</td>
                                <td>{{ reservation.reservation_date_time|date:"d-m-Y G:i"  }}</td>
                                <td>
                                    {% if reservation.status == 'Cho xu ly' %}<span class="badge badge-pill badge-secondary">Cho xu ly</span>
                                    {% elif reservation.status == 'Da dat phong' %}<span class="badge badge-pill badge-success">Da dat phong</span>
                                    {% else %}<span class="badge badge-pill badge-warning">Da huy</span>
                                    {% endif %}
                                       </td>
                                <td>
                                    {% if reservation.status == 'Cho xu ly' %}
                                        {% if perms.reservation.change_reservation %}<a class="badge badge-primary" href="{% url 'reservation_update' reservation.id %}">Xu ly</a>{% endif %}
                                    {% endif %}
                                    {% if perms.reservation.view_reservation %}<a href="{{ reservation.get_absolute_url }}" class="badge badge-info">Chi tiet</a>{% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script type="text/javascript" language="javascript" src="{% static 'media/js/jquery.dataTables.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'media/js/dataTables.uikit.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/syntax/shCore.js' %}"></script>
	<script type="text/javascript" language="javascript" src="{% static 'resources/demo.js' %}"></script>
    <script type="text/javascript" language="javascript" class="init">

$(document).ready(function() {
	$('#example').DataTable();
} );
    </script>

{% endblock %}