blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('category/list', views.CategoryListView.as_view(), name='category_list'),
    path('category/create', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/<slug:slug>/update', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<slug:slug>/delete', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('', views.ReservationCreateView.as_view(), name='blog_home'),
    path('room', views.BlogRoomListView.as_view(), name='blog_room'),
    path('about', views.AboutView.as_view(), name='blog_about'),
    path('contact', views.ContactView.as_view(), name='blog_contact'),
    path('articles', views.BlogArticleListView.as_view(), name='blog_article_list'),
    path('<slug:slug>', views.BlogArticleDetailView.as_view(), name='blog_article_detail'),
    path('category/<slug:slug>', views.BlogCategoryDetailView.as_view(), name='blog_category_detail'),
    path('<slug:slug>/send-comment', views.send_comment, name='blog_send_comment'),
    path('tag/<slug:slug>', views.BlogTagDetailView.as_view(), name='blog_tag_detail'),
    path('articles/search', views.ArticleSearchListView.as_view(), name='article_search_list_view'),
    path('author/<int:pk>', views.AuthorArticlesListView.as_view(), name='blog_author_articles'),

    path('article/<slug:slug>', views.DashboardArticleDetailView.as_view(), name='dashboard_article_detail'),
    path('article/list/', views.DashboardArticleListView.as_view(), name='dashboard_article_list'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<slug:slug>/update', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/<slug:slug>/delete', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/<int:pk>/update', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('myarticle/', views.UserArticlesListView.as_view(), name='my_articles'),

    path('article/category/create', views.CategoryCreatePopup, name="category_create_popup"),
    path('article/category/ajax/get_category_id', views.get_category_id, name="get_customer_id"),
]

dashboard/urls.py
from django.urls import path
from . import views
from .views import Dashboard

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
]

django_hotel_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView
from django.urls import path, include, reverse_lazy, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from booking.api import ServiceViewSet, BookingTypeViewSet, BookingViewSet, CheckInViewSet, CheckOutViewSet
from customer.api import CustomerViewSet
from reservation.api import ReservationViewSet
from room.api import RoomViewSet, RoomTypeViewSet, FacilityViewSet
from blog.api import CategoryViewSet, ArticleList, CategoryArticleList, ArticleViewSet, ArticleCommentList, \
    CommentRetrieveUpdateDestroy, CommentList
from dashboard.forms import PasswordChangeForm, ResetPasswordForm, SetPasswordForm
from dashboard.views import loginrequest, registeruser, UserProfileView
from staff.api import StaffRoleViewSet, StaffViewSet

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),

    path('userprofile/', UserProfileView.as_view(), name='userprofile'),
    path('changepassword/',
         PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm,
                                    success_url=reverse_lazy('dashboard')), name='changepassword'),
    path('passwordreset/',
         PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm,
                                   success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'),
         name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm,
                                          success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),
]

urlpatterns += [
    path('booking/', include('booking.urls')),
    path('customers/', include('customer.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('reservation/', include('reservation.urls')),
    path('rooms/', include('room.urls')),
    path('staffs/', include('staff.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-catalog')
]

router = routers.DefaultRouter()
router.register(r'rooms', RoomViewSet, 'room')
router.register(r'room-types', RoomTypeViewSet, 'room-type')
router.register(r'facilities', FacilityViewSet, 'facility')
router.register(r'categories', CategoryViewSet, 'category')
router.register(r'articles', ArticleViewSet, 'article')
router.register(r'services', ServiceViewSet, 'service')
router.register(r'booking-types', BookingTypeViewSet, 'booking-type')
router.register(r'bookings', BookingViewSet, 'booking')
router.register(r'checkins', CheckInViewSet, 'checkin')
router.register(r'checkouts', CheckOutViewSet, 'checkout')
router.register(r'customers', CustomerViewSet, 'customer')
router.register(r'reservations', ReservationViewSet, 'reservation')
router.register(r'staff-roles', StaffRoleViewSet, 'staff-role')
router.register(r'staffs', StaffViewSet, 'staff')


urlpatterns += [
    path('api/articlelist/', ArticleList.as_view()),
    path('api/category-articles/<slug:slug>/', CategoryArticleList.as_view()),
    path('api/article-comments/<slug:slug>/', ArticleCommentList.as_view()),
    path('api/comments/', CommentList.as_view()),
    path('api/comments/<int:pk>/', CommentRetrieveUpdateDestroy.as_view()),
    path('api/', include(router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from math import ceil

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from customer.models import Customer
from reservation.models import Reservation
from room.models import Room
from staff.models import Staff


class Service(models.Model):
    service_type = models.CharField('Dich vu', max_length=50)
    service_price = models.FloatField('Gia', default=0)

    class Meta:
        ordering = ['service_price', 'service_type']

    def __str__(self):
        return self.service_type


class BookingType(models.Model):
    booking_type = models.CharField('Hinh thuc dat phong', max_length=50)

    def __str__(self):
        return self.booking_type


class Booking(models.Model):
    booking_type = models.ForeignKey(BookingType, on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Nguoi thuc hien')
    no_of_adults = models.PositiveSmallIntegerField(default=1, verbose_name='So nguoi lon')
    no_of_children = models.PositiveSmallIntegerField(default=0, verbose_name='So tre em')
    booking_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay dat phong')
    arrival_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay den')
    departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay du kien di')
    description = models.CharField("Yeu cau cua khach hang", max_length=3000, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')
    canceled = models.BooleanField(default=False, verbose_name='Huy dat truoc', blank=True, null=True)

    class Meta:
        ordering = ['arrival_date_time', 'booking_date_time']

    def get_absolute_url(self):
        return reverse('booking_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.customer}'

    def total_guest(self):
        return self.no_of_adults + self.no_of_children

    @property
    def is_over_arrival_time(self):
        if self.arrival_date_time and timezone.now() > self.arrival_date_time:
            return True
        return False


class CheckIn(models.Model):
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE, null=True)
    rooms = models.ManyToManyField(Room, verbose_name='Phong thue')
    services = models.ManyToManyField(Service, verbose_name='Dich vu')
    departure_date_time = models.DateTimeField(default=timezone.now, verbose_name='Ngay du tra phong')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Nguoi checkin')
    checkin_time = models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check in')
    initial_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tien/ngay')

    updated_at = models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')

    class Meta:
        ordering = ['-checkin_time']

    def get_absolute_url(self):
        return reverse('checkin_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.booking.customer.customer_name}'

    def save(self, *args, **kwargs):
        initial_amount = 0
        for room in self.rooms.all():
            initial_amount += room.room_type.price
            for service in self.services.all():
                initial_amount += service.service_price
        self.initial_amount = initial_amount
        super().save(*args, **kwargs)

    @property
    def is_over_departure_time(self):
        if self.departure_date_time and timezone.now() > self.departure_date_time:
            return True
        return False


class CheckOut(models.Model):
    PAYMENT_TYPE = (
        ('Tien mat', 'Tien mat'),
        ('Chuyen khoan', 'Chuyen khoan'),
        ('The thanh toan', 'The thanh toan'),
    )
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    checkin = models.OneToOneField(CheckIn, on_delete=models.CASCADE)

    checkout_time = models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check out')
    stay_duration = models.DurationField(null=True, editable=False, verbose_name='Thoi gian luu tru')
    total_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tong chi phi')
    pay_amount = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Thanh tien')

    extra_fee = models.FloatField('Phu phi', default=0)
    discount = models.FloatField('Khuyen mai', default=0)
    vat = models.FloatField("VAT", default=10)
    payment_type = models.CharField('Hinh thuc thanh toan', choices=PAYMENT_TYPE, max_length=20, default='Tien mat')
    checkout_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Nguoi thanh toan")

    class Meta:
        ordering = ['checkout_time']

    def get_absolute_url(self):
        return reverse('checkout_detail', args=[str(self.id)])

    def __str__(self):
        return f'({self.id}) {self.checkin.booking.customer.customer_name}'

    def save(self, *args, **kwargs):
        stay_time = self.checkout_time - self.checkin.checkin_time
        calculated_duration = timezone.timedelta(days=ceil(stay_time.total_seconds() / 3600 / 24))
        self.stay_duration = calculated_duration
        self.total_amount = calculated_duration.days * self.checkin.initial_amount + self.extra_fee
        amount_with_vat = self.total_amount + self.total_amount * self.vat / 100
        self.pay_amount = amount_with_vat - amount_with_vat * self.discount / 100
        super().save(*args, **kwargs)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


class Profile(models.Model):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, _("Nam")),
        (GENDER_FEMALE, _("Nu")),
    ]

    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    avatar = models.ImageField(null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    quote = models.CharField(max_length=255, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

room/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Facility(models.Model):
    facility_type = models.CharField('Co so vat chat', max_length=50, unique=True, error_messages={'unique':"truong thong tin da ton tai"})

    def __str__(self):
        return self.facility_type


class RoomType(models.Model):
    type = models.CharField('Loai phong', max_length=50, unique=True, error_messages={'unique':"Loai phong da ton tai"})
    facility = models.ManyToManyField(Facility, verbose_name='Co so vat chat')
    description = models.CharField('Mo ta', max_length=1000, null=True, blank=True)
    price = models.FloatField('Gia phong')

    class Meta:
        ordering = ['price']

    def __str__(self):
        return self.type


class Room(models.Model):
    room_number = models.CharField('So phong', primary_key=True, max_length=30, error_messages={'unique':"Phong da ton tai"})
    room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True, verbose_name="Loai phong")
    maintenance = models.BooleanField(default=False, verbose_name='Bao tri')
    availability = models.BooleanField(default=True, verbose_name='Co the su dung')

    class Meta:
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.room_number} - {self.room_type}'

    def get_absolute_url(self):
        return reverse('room_detail', args=[str(self.room_number)])

staff/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class StaffRole(models.Model):
    role = models.CharField('Bo phan', max_length=50)

    def __str__(self):
        return self.role


class Staff(models.Model):
    GENDER = (
        ('M', 'Nam'),
        ('F', 'Nu'),
    )
    staff_id = models.CharField('Ma nhan vien', primary_key=True, max_length=10,
                                error_messages={'unique': "Ma nhan vien da ton tai"})
    first_name = models.CharField('Ho va ten dem', max_length=50)
    last_name = models.CharField('Ten', max_length=50)
    staff_role = models.ForeignKey(StaffRole, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Bo phan')
    staff_email = models.EmailField('Email', unique=True, error_messages={'unique': "Email da duoc su dung"})
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, editable=False)

    class Meta:
        ordering = ['first_name', 'last_name', 'staff_id']

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

    def get_absolute_url(self):
        return reverse('staff_detail', args=[str(self.staff_id)])

dashboard/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block header_static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' %}">
    <!-- animation css -->
    <link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">

    <!-- morris css -->
    <link rel="stylesheet" href="{% static 'plugins/chart-morris/css/morris.css' %}">

    <!-- vendor css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block styles %}{% endblock %}

{% block content %}
<!-- [ Main Content ] start -->
    <h2>Thong ke so lieu thang {{ today.month }}/{{ today.year }}</h2>
<div class="container m-0 p-0">
    <div class="row m-0 p-0">
        <div class="col-md-12 col-xl-4 m-0 p-0">
            <div class="row m-0 p-0 justify-content-md-center">
                <div class="col-12 m-0 p-0">
                    <div class="card card-social">
                        <div class="card-block border-bottom">
                            <div class="row align-items-center justify-content-center">
                                <div class="col-auto">
                                    <i class="fa fa-dollar-sign text-primary f-40"></i>
                                </div>
                                <div class="col text-right">
                                    <h3>Doanh thu ${{ total_profit_this_month|intcomma }}</h3>
                                    {% if checkin_growth_month >= 0 %}<h5 class="text-c-green mb-0">+{% else %}<h5 class="text-c-red mb-0">{% endif %}{{ checkin_growth_month|floatformat:1 }}%
                                        <span class="text-muted">So voi thang {{ last_month.month }}/{{ last_month.year }}</span></h5>
                                </div>
                            </div>
                        </div>
                        <div class="card-block">
                            <div class="row align-items-center justify-content-center card-active">
                                <div class="col-6">
                                    <h6 class="text-center m-b-10"><span class="text-muted m-r-5">Chi tieu:</span>{{ target|intcomma }}</h6>
                                    <div class="progress">
                                        <div class="progress-bar progress-c-blue" role="progressbar" style="width:{{ target_now }}%;height:6px;" aria-valuenow="{{ target_now }}" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <h6 class="text-center  m-b-10"><span class="text-muted m-r-5">Thoi han:</span>{{ duration_target }} ngay</h6>
                                    <div class="progress">
                                        <div class="progress-bar progress-c-green" role="progressbar" style="width:{{ duration_target_percent }}%;height:6px;" aria-valuenow="{{ duration_target_percent }}" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row m-0 p-0">
                <div class="col-12 p-0 m-0">
                    <div class="card prod-p-card bg-c-blue">
                        <div class="card-body">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h6 class="m-b-5 text-white">Tong so Checkin</h6>
                                    <span class="m-b-0 text-white h5">{{ checkin_this_month }} </span><span class="label label-primary m-r-10"> {% if checkin_growth_month >= 0 %}+{% endif %}{{ checkin_growth_month|floatformat:1 }}%</span>
                                </div>
                                <div class="col-4">
                                    <i class="fas fa-database text-c-blue f-18"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row m-0 p-0">
                <div class="col-12 p-0 m-0">
                    <div class="card prod-p-card bg-c-yellow">
                        <div class="card-body">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h6 class="m-b-5 text-white">Khach hang moi</h6>
                                    <span class="m-b-0 text-white h5">{{ new_customers_this_month }} </span><span class="label label-warning m-r-10"> {% if checkin_growth_month >= 0 %}+{% endif %}{{ checkin_growth_month|floatformat:1 }}%</span>
                                </div>
                                <div class="col-4">
                                    <i class="fas fa-users text-c-yellow f-18"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ line-smooth Chart ] start -->
        <div class="col-md-12 col-xl-8">
            <div class="card">
                <div class="card-header">
                    <h5>Thang {{ today.month }}/{{ today.year }}</h5>
                </div>
                <div class="card-body">
                    <div id="profit-month-chart" class="ChartShadow" style="height:300px"></div>
                </div>
            </div>
        </div>
        <!-- [ line-smooth Chart ] end -->
    </div>
    <div class="row">
        <!-- product profit start -->
        <div class="col-md-4 col-xl-4">
            <div class="row">
                <div class="col card prod-p-card bg-c-red">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-b-5 text-white">Giao dich dat phong: {{ booking_this_month_count }}</h6>
                                <p class="m-b-5 text-white"><span class="label label-danger m-r-10">{% if booking_growth_month >= 0 %}+{% endif %}{{ booking_growth_month|floatformat:1 }}%</span>So voi thang {{ last_month.month }}/{{ last_month.year }}</p>
                                <h6 class="m-b-5 text-white">Bi huy: {{ booking_cancel_this_month }} ({{ booking_cancel_this_month_percent|floatformat:1 }}%)</h6>
                                <h3 class="m-b-5 text-white"><a class="text-white" href="{% if perms.booking.view_checkin %}{% url 'booking_list' %}{% endif %}">Chua checkin: {{ booking_pending }}</a></h3>
                                <h6 class="m-b-5 text-white"><a class="text-white" href="{% if perms.reservation.view_reservation %}{% url 'reservation_list' %}{% endif %}">Dat cho truoc chua xu ly: {{ reservation_pending }}</a></h6>
                            </div>
                            <div class="col-auto">
                                <i class="fas fas fa-book text-c-red f-18"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col card prod-p-card bg-c-green">
                    <div class="card-body">
                        <div class="row align-items-center m-b-10">
                            <div class="col">
                                <h6 class="m-b-5 text-white">Tong so phong: {{ total_room }}</h6>
                                <h3 class="m-b-5 text-white"><a class="text-white" href="{% if perms.room.view_room %}{% url 'room_list' %}{% endif %}">San sang su dung: {{ rooms_available.count }}</a></h3>
                                {% for roomtype, count in room_in_roomtype.items %}
                                    <li class="m-b-0 text-white">{{ roomtype }}: {{ count }}</li>
                                {% endfor %}
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-home text-c-green f-18"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xl-4">
            <div class="card">
                <div class="card-header">
                    <a href="{% if perms.booking.view_booking %}{% url 'booking_list' %}{% endif %}"><h3 class="m-0 p-0">Dat phong thang {{ today.month }}/{{ today.year }}</h3></a><p class="m-0 p-0">Tong so: {{ booking_this_month_count }}</p>
                </div>
                <div class="card-body">
                    <div id="booking-chart" style="height:250px"></div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xl-4">
            <div class="card">
                <div class="card-header">
                    <a class="text-white" href="{% if perms.staff.view_staff %}{% url 'staff_list' %}{% endif %}"><h3 class="m-0 p-0">Nhan vien</h3></a><p class="m-0 p-0">Tong so: {{ total_staff }}</p>
                </div>
                <div class="card-body">
                    <div id="staff-chart" style="height:250px"></div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}

    <!-- chart-morris Js -->
    <script src="{% static 'js/pages/chart-morris-custom.js' %}"></script>
    <script src="{% static 'plugins/chart-morris/js/raphael.min.js' %}"></script>
    <script src="{% static 'plugins/chart-morris/js/morris.min.js' %}"></script>

    <script>
$(document).ready(function() {
    setTimeout(function () {
        <!-- profit-month-chart -->
        Morris.Line({
            element: 'profit-month-chart',
            data: [
                {% for period in recurring_profit %}
                    {y: '{{ period.0 }}', a: {{ period.1|safe }}, b: {{ period.2|safe }} },
                {% endfor %}
            ],
            xkey: 'y',
            xLabels: "",
            parseTime: false,
            redraw: true,
            resize: true,
            ykeys: ['a', 'b'],
            hideHover: 'auto',
            responsive: true,
            labels: ['Thang {{ today.month }}', 'Thang {{ last_month.month }}'],
            lineColors: ['#2ca961', '#e52d27']
        });
        <!-- profit-month-chart end -->

        <!-- booking-chart-->
        var graph = Morris.Donut({
            element: 'staff-chart',
            data: [
                {% for role in staff_role %}
                    {value: {{ role.staff_set.count|safe }}, label: '{{ role|safe }}' },
                {% endfor %}
            ],
            colors: ['#3949AB','#463699','#e52d27','#f57c00', '#3effab', '#ff2b6d', '#a5533d', '#3b2747', '#f9b71a'],
            resize: true,
            formatter: function(x) {
                return x + ' nguoi'
            }
        });
        <!-- booking-chart end-->

        <!-- staff-chart-->
        var graph = Morris.Donut({
            element: 'booking-chart',
            data: [
                {% for type, count in booking_type_this_month.items %}
                    {value: {{ count|safe }}, label: '{{ type|safe }}'},
                {% endfor %}
            ],
            colors: ['#9e0d26','#57b5bb','#f9b71a','#982477','#480aa4', '#3949AB'],
            resize: true,
            formatter: function(x) {
                return x + ' luot'
            }
        });
        <!-- staff-chart end-->

    });
});
        // [ bar-simple ] chart end
    </script>
{% endblock %}